name: Run format check on pull request

on: pull_request

jobs:
  run-format-check-on-pull-request:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./DotNetBackend

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run format check
        run: dotnet format . --folder --check
